// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestdoanTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testdoan() {
    driver.Navigate().GoToUrl("http://localhost:30084/Main/addsp");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    driver.FindElement(By.LinkText("Xem sản phẩm")).Click();
    driver.FindElement(By.LinkText("Duyệt Đơn Hàng")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(8)")).Click();
    driver.FindElement(By.Name("2")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(2) > td:nth-child(8)")).Click();
    driver.FindElement(By.Name("1")).Click();
    driver.FindElement(By.CssSelector(".btn-secondary")).Click();
    driver.FindElement(By.CssSelector("ul:nth-child(1) > li:nth-child(3)")).Click();
    driver.FindElement(By.LinkText("Thống Kê")).Click();
  }
}
