// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestDatHangTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testDatHang() {
    driver.Navigate().GoToUrl("http://localhost:30084/");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    driver.FindElement(By.LinkText("Mua")).Click();
    driver.FindElement(By.CssSelector(".navbar span")).Click();
    driver.FindElement(By.LinkText("Mua Hàng")).Click();
    driver.FindElement(By.Name("diachigiao")).Click();
    driver.FindElement(By.Name("diachigiao")).SendKeys("fsgsg");
    driver.FindElement(By.Name("ngaygiao")).Click();
    driver.FindElement(By.Name("ngaygiao")).SendKeys("2022-06-16");
    driver.FindElement(By.CssSelector(".btn-secondary")).Click();
  }
}
