// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TestTrangChuTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testTrangChu() {
    driver.Navigate().GoToUrl("http://localhost:30084/");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
    driver.FindElement(By.LinkText("Trang Chủ")).Click();
    driver.FindElement(By.LinkText("Sản phẩm")).Click();
    driver.FindElement(By.LinkText("Liên hệ")).Click();
    driver.FindElement(By.Id("menudrop")).Click();
    driver.FindElement(By.LinkText("Action")).Click();
    driver.FindElement(By.Name("txtTuKhoa")).Click();
    driver.FindElement(By.Name("txtTuKhoa")).SendKeys("độc bộ tiêu dao");
    driver.FindElement(By.Name("txtTuKhoa")).Click();
    driver.FindElement(By.Name("txtTuKhoa")).SendKeys("Khô cốt hiệp sĩ SP01");
    driver.FindElement(By.CssSelector(".input-group > a")).Click();
    driver.FindElement(By.Name("txtTuKhoa")).Click();
    driver.FindElement(By.Name("txtTuKhoa")).SendKeys("Khô cốt hiệp sĩ ");
    driver.FindElement(By.CssSelector(".btn-outline-primary")).Click();
  }
}
